export enum SubjectCode {
  MATH = 'MATH',
  LITERATURE = 'LITERATURE',
  FOREIGN_LANGUAGE = 'FOREIGN_LANGUAGE',
  PHYSICS = 'PHYSICS',
  CHEMISTRY = 'CHEMISTRY',
  BIOLOGY = 'BIOLOGY',
  HISTORY = 'HISTORY',
  GEOGRAPHY = 'GEOGRAPHY',
  CIVIC_EDUCATION = 'CIVIC_EDUCATION',
}
